### ISSUE TITLE
Is some of the code still closed???

### ISSUE THREAD

**Issue by MrMEEE** [feedhenry/fh-mbaas#112]
Hi guys..

I'm trying to get feedhenry to run.. 

When starting, I get:

```
scl enable rh-nodejs6 "node ./fh-mbaas.js config/conf.json --master-only"
starting single master process
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":20,"msg":"JSON Config  { mongoUrl: 'mongodb://localhost:27017/fh-mbaas',\n  mongo: \n   { host: 'localhost',\n     port: 27017,\n     name: 'fh-mbaas',\n     admin_auth: { user: 'mbaas', pass: 'password' },\n     replicaSet: null },\n  crash_monitor: \n   { enabled: true,\n     min_num_crashes: 10,\n     max_num_crashes: 40,\n     tolerance: 1,\n     base_time_seconds: 60,\n     sample_time_hrs: 1 },\n  email: \n   { transport: '',\n     sendgrid: { auth: [Object] },\n     smtp: 'smtps://user:password@smtp.example.com',\n     alert_email_from: 'no-reply@feedhenry.com',\n     alert_email_bcc: '' },\n  fhamqp: \n   { app: { enabled: true },\n     enabled: true,\n     max_connection_retry: 10,\n     ssl: false,\n     nodes: 'node1:5672',\n     vhosts: { events: [Object], internal: [Object] } },\n  logger: \n   Logger {\n     domain: null,\n     _events: {},\n     _eventsCount: 0,\n     _maxListeners: undefined,\n     _level: 10,\n     streams: [ [Object], [Object] ],\n     serializers: { req: [Function: requestSerializer], res: [Function: res] },\n     src: false,\n     fields: \n      { name: 'mbaas',\n        hostname: 'feedhenry.casalogic.lan',\n        pid: 27333 },\n     requestIdMiddleware: { [Function: middleware] header: 'X-FH-REQUEST-ID' },\n     requestIdHeader: 'X-FH-REQUEST-ID',\n     getRequestId: [Function: getRequestId],\n     setRequestId: [Function: setRequestId],\n     getLoggerNamespace: [Function: getLoggerNamespace],\n     ensureRequestId: [Function: ensureRequestId],\n     fatal: [Function],\n     error: [Function],\n     warn: [Function],\n     info: [Function],\n     debug: [Function],\n     trace: [Function] },\n  mongoUserUrl: 'mongodb://localhost:27017/fh-mbaas',\n  mongo_userdb: \n   { host: 'localhost',\n     port: 27017,\n     name: 'fh-mbaas',\n     admin_auth: { user: 'mbaas', pass: 'password' },\n     replicaSet: null } }","time":"2018-05-15T11:20:23.541Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":20,"msg":"setup mongodb connections { mongoConnectionString: 'mongodb://localhost:27017/fh-mbaas',\n  config: { auth: { user: 'mbaas', pass: 'password' }, poolSize: 20 } }","time":"2018-05-15T11:20:23.746Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":20,"msg":"formated mongo connection url { mongoDbUrl: 'mongodb://mbaas:password@localhost:27017/admin?poolSize=20' }","time":"2018-05-15T11:20:23.747Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":20,"msg":"creating mongodb connection for data_source_update job { mongoDbUrl: 'mongodb://mbaas:password@localhost:27017/admin?poolSize=20' }","time":"2018-05-15T11:20:23.748Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":50,"msg":"Cannot find ops info file.  { location: '/etc/feedhenry/openv.json' }","time":"2018-05-15T11:20:23.893Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":40,"msg":"Connecting to amqp with prefix . ops file path /etc/feedhenry/openv.json","time":"2018-05-15T11:20:23.894Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":30,"msg":"Subscribing to amqp queue { exchangeName: '-fh-internal',\n  queueName: 'fh--appDeployStatus' }","time":"2018-05-15T11:20:23.894Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":20,"msg":"JSON Config  { mongoUrl: 'mongodb://localhost:27017/fh-mbaas',\n  mongo: \n   { host: 'localhost',\n     port: 27017,\n     name: 'fh-mbaas',\n     admin_auth: { user: 'mbaas', pass: 'password' },\n     replicaSet: null },\n  crash_monitor: \n   { enabled: true,\n     min_num_crashes: 10,\n     max_num_crashes: 40,\n     tolerance: 1,\n     base_time_seconds: 60,\n     sample_time_hrs: 1 },\n  email: \n   { transport: '',\n     sendgrid: { auth: [Object] },\n     smtp: 'smtps://user:password@smtp.example.com',\n     alert_email_from: 'no-reply@feedhenry.com',\n     alert_email_bcc: '' },\n  fhamqp: \n   { app: { enabled: true },\n     enabled: true,\n     max_connection_retry: 10,\n     ssl: false,\n     nodes: 'node1:5672',\n     vhosts: { events: [Object], internal: [Object] } },\n  logger: \n   Logger {\n     domain: null,\n     _events: {},\n     _eventsCount: 0,\n     _maxListeners: undefined,\n     _level: 10,\n     streams: [ [Object], [Object] ],\n     serializers: { req: [Function: requestSerializer], res: [Function: res] },\n     src: false,\n     fields: \n      { name: 'mbaas',\n        hostname: 'feedhenry.casalogic.lan',\n        pid: 27333 },\n     requestIdMiddleware: { [Function: middleware] header: 'X-FH-REQUEST-ID' },\n     requestIdHeader: 'X-FH-REQUEST-ID',\n     getRequestId: [Function: getRequestId],\n     setRequestId: [Function: setRequestId],\n     getLoggerNamespace: [Function: getLoggerNamespace],\n     ensureRequestId: [Function: ensureRequestId],\n     fatal: [Function],\n     error: [Function],\n     warn: [Function],\n     info: [Function],\n     debug: [Function],\n     trace: [Function],\n     haveNonRawStreams: true },\n  mongoUserUrl: 'mongodb://localhost:27017/fh-mbaas',\n  mongo_userdb: \n   { host: 'localhost',\n     port: 27017,\n     name: 'fh-mbaas',\n     admin_auth: { user: 'mbaas', pass: 'password' },\n     replicaSet: null } }","time":"2018-05-15T11:20:23.896Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":30,"msg":"Initialising scheduler.","time":"2018-05-15T11:20:23.897Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":30,"msg":"Setting up Agenda 27333","time":"2018-05-15T11:20:23.897Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":30,"msg":"Initialised scheduler { tearDown: [Function: tearDown] }","time":"2018-05-15T11:20:23.908Z","v":0}
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":50,"msg":"FATAL: UncaughtException, please report: { Error: Cannot find module 'fh-dfc'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/util/dfutils.js:8:15)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/preparationSteps.js:6:15)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/AppDataExportRunner.js:8:17)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/jobs/appDataJob.js:5:67)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }","time":"2018-05-15T11:20:23.999Z","v":0}
Tue May 15 2018 13:20:24 GMT+0200 (CEST) FATAL: UncaughtException, please report: { Error: Cannot find module 'fh-dfc'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/util/dfutils.js:8:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/preparationSteps.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/AppDataExportRunner.js:8:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/jobs/appDataJob.js:5:67)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{"name":"mbaas","hostname":"feedhenry.casalogic.lan","pid":27333,"level":50,"msg":"'Error: Cannot find module \\'fh-dfc\\'\\n    at Function.Module._resolveFilename (module.js:469:15)\\n    at Function.Module._load (module.js:417:25)\\n    at Module.require (module.js:497:17)\\n    at require (internal/module.js:20:19)\\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/util/dfutils.js:8:15)\\n    at Module._compile (module.js:570:32)\\n    at Object.Module._extensions..js (module.js:579:10)\\n    at Module.load (module.js:487:32)\\n    at tryModuleLoad (module.js:446:12)\\n    at Function.Module._load (module.js:438:3)\\n    at Module.require (module.js:497:17)\\n    at require (internal/module.js:20:19)\\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/preparationSteps.js:6:15)\\n    at Module._compile (module.js:570:32)\\n    at Object.Module._extensions..js (module.js:579:10)\\n    at Module.load (module.js:487:32)\\n    at tryModuleLoad (module.js:446:12)\\n    at Function.Module._load (module.js:438:3)\\n    at Module.require (module.js:497:17)\\n    at require (internal/module.js:20:19)\\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/AppDataExportRunner.js:8:17)\\n    at Module._compile (module.js:570:32)\\n    at Object.Module._extensions..js (module.js:579:10)\\n    at Module.load (module.js:487:32)\\n    at tryModuleLoad (module.js:446:12)\\n    at Function.Module._load (module.js:438:3)\\n    at Module.require (module.js:497:17)\\n    at require (internal/module.js:20:19)\\n    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/jobs/appDataJob.js:5:67)\\n    at Module._compile (module.js:570:32)\\n    at Object.Module._extensions..js (module.js:579:10)\\n    at Module.load (module.js:487:32)\\n    at tryModuleLoad (module.js:446:12)\\n    at Function.Module._load (module.js:438:3)'","time":"2018-05-15T11:20:24.000Z","v":0}
Trace: Error: Cannot find module 'fh-dfc'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/util/dfutils.js:8:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/preparationSteps.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/export/AppDataExportRunner.js:8:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/feedhenry/fh-mbaas/lib/jobs/appDataJob.js:5:67)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at process.<anonymous> (/opt/feedhenry/fh-mbaas/fh-mbaas.js:399:15)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
    at process._asyncFatalException [as _fatalException] (/opt/feedhenry/fh-mbaas/node_modules/fh-forms/node_modules/fh-logger/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:211:34)
```

I can't find the fh-dfc module anywhere????

Is that still closed source???

**Comment by camilamacedo86** [comment]
@MrMEEE yes. Have you an RHMAP subscription? Please, could you open a support case related to it?
Please, let me know if you are able to open the support case and if we can address this subject in this way.  

c/c @davidffrench @mmurphy

**Comment by MrMEEE** [comment]
@camilamacedo86 Well, I work as a Senior Consultant at a Red Hat Premium Partner, so I could get a NFR subscription.. But this was not a question addressed to Red Hat Mobile Platform..

I wanted to play around with the upstream version.. but what you are saying is that it has still not been completely open sourced??? It has been a couple of years now...

**Comment by davidffrench** [comment]
Hey @MrMEEE, The vast majority of the RHMAP components have been open sourced, this fh-mbaas component being one. The fh-dfc module has not been. 

If you are interested in contributing or getting involved in Mobile within Red Hat, I would highly recommend looking at our still in development next Mobile product. the entirety of it has been open from the start, all repos are open sourced and available in the AeroGear organisation https://github.com/aerogear.

**Comment by MrMEEE** [comment]
hi @davidffrench

Thanks for the info.. I just think it's weird that it hasn't been open sourced after 3½ years?? I thought Red Hat was committed to open source everything...

What is the core functionality in Aerogear compared to Feedhenry?.. The stuff I am interested in testing and working with is the functionality to be able to create simple webapps, like in Feedhenry...

**Comment by MrMEEE** [comment]
Hi..

In regards to open sourcing.. FeedHenry is useless without dfc module, besides inspiring.. I don't see why Red Hat shouldn't be able to open source the rest of the project...

I'm not interested in a framework.. i'm interested to test the WYSIWYG kind of approach that Feedhenry is implementing.. I have tested in RHMAP, and I see a a lot of potential for our customers.. 

A lot of the customers would be interested in testing out, and in the long run purchase a solution like this.. but the relatively short testing phase that Red Hat offers (1-3 months) are not enough.. 

So what we have done at alot of customers is to implement the community version of projects.. and then moved the customer to the enterprise version later.. We have used this strategy for things like RHEV, Ansible Tower, OpenShift and GlusterFS.. And it works...

**Comment by camilamacedo86** [comment]
@MrMEEE, 

Thank you for raise this point. We will check it internally and we will let you know. 

Cheers,

**Comment by MrMEEE** [comment]
@camilamacedo86 Hi.. Any news in regards to this?

**Comment by camilamacedo86** [comment]
Hi @MrMEEE the fh-dfc is a closed lib and are plans to make it public. You can use this project since it is public, however, you will not able to run locally test tasks where the fh-dfc is required. I'd like to recommend open a support case if you wish in order to request it and suggest to you check the aerogear projects as suggested in the above comment.

**Comment by camilamacedo86** [comment]
@davidffrench I think we could close this issue since the answers were already provided. @MrMEEE have you any objection?

**Comment by MrMEEE** [comment]
@camilamacedo86 I have created a support case @RedHat..

As I have written earlier, I'm well aware that there are alternatives to Feedhenry/Mobile Platform.. but that's not what I'm interested in here.. I'm actually trying to help Red Hat to get Mobile Platform sold to more customers..

I think this issue should be kept open as a tracker, especially if the there are plans to make the fh-dfc module (and others?) public..

**Comment by camilamacedo86** [comment]
@MrMEEE could you let us the number of the support case that you opened? 
Sorry, I think has some misunderstand. The product team do NOT have plans to make this lib public. Regards the "actually trying to help Red Hat to get Mobile Platform sold to more customers.." I'd like to recommend you speak with your account manager about this subject.

**Comment by MrMEEE** [comment]
@camilamacedo86 case number #2234076 .. then you have got a typo: " the fh-dfc is a closed lib and are plans to make it public.".. 

I talked with my account manager multiple times, but it's going nowhere..

**Comment by camilamacedo86** [comment]
Hi @MrMEEE.

Thank you. I saw that the case was opened today, 2018-10-18, with this request.  Please, follow up the case in order to get updates about it.  There is the best channel. Also, sorry you are correct. I did not write properly the explanation. Regards your wish about sell RHMAP, I strongly recommend you speak with your account manager/partner. I am closing this now. I hope that we can agree with move forward in this way. 

Cheers,

**Comment by davidffrench** [comment]
Thanks @MrMEEE , I really appreciate your enthusiasm in open source and RHMAP as a product. Just to reiterate what @camilamacedo86 has said above, the product team do not have any plans on making this lib public and I would second Camila's comment on speaking with your account manager in relation to selling RHMAP or contacting the mobile product management team.

**Comment by mjaperta** [comment]
@davidffrench @camilamacedo86 Any update on this case, or is it still the same answer?

**Comment by MrMEEE** [comment]
@davidffrench @camilamacedo86 Any update on this case, or is it still the same answer?

**Comment by davidffrench** [comment]
Hi @MrMEEE No update from our side, there have been no changes on opinion from the product team.

**Comment by MrMEEE** [comment]
Too bad.. thanks for replying..

**Comment by MrMEEE** [comment]
@davidffrench @camilamacedo86 Checking back in on this.. any updates?

**Comment by davidffrench** [comment]
@MrMEEE As we progressed open sourcing the FeedHenry codebase, it was determined that the level of level of effort required to open source some remaining legacy modules (over and above focusing on the development of our next generation offering, powered by Red Hat OpenShift - the leading hybrid cloud platform) could not be justified.

As a result, we diverted our investment in the FeedHenry codebase towards the AeroGear project (aerogear.org) which is fully open sourced. The AeroGear website is in the process of being updated, if you have any specific questions, technical or otherwise around the AeroGear project, please reach out on the mailing list directly (aerogear@googlegroups.com)
